title: My profile
description: Antonis Mikroutsikos profile
author: Mikroutsikos Antonis
avatar: /logo.png
email: mikroutsikos.antonis@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Mikroutsikos Antonis
  card: summary
logo: logo.png
social:
  name: Mikroutsikos Antonis
  links:
    - https://github.com/Antonis-Mikroutsikos
    - https://www.linkedin.com/in/a-mikroutsikos/
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
